# --- CONFIGURACIÓN DE H2 ---
spring.datasource.url=jdbc:h2:mem:garage;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Mostrar la consola web de H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# --- JPA / HIBERNATE ---
# Hibernate crea las tablas automáticamente desde las entidades.
# No se necesita schema.sql ni data.sql.
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Desactivar la ejecución de schema.sql y data.sql
spring.sql.init.mode=never

logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.orm.jdbc.bind=trace
spring.jpa.properties.hibernate.hbm2ddl.halt_on_error=true